[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = ""
  CONTENTFUL_ACCESS_TOKEN = ""
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = ""

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://app.contentful.com"

[[redirects]]
  from = "/"
  to = "/home/"
  status = 301
  force = true